# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seoul Parking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
 
  
  # Pods for Seoul Parking
  
  #Google Maps
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  #Naver Login
  pod 'naveridlogin-sdk-ios'
  
  #Kakao Login
  
  #Kakao Navi
  pod 'KakaoSDK'
  
  #Facebook Login
  pod 'FBSDKLoginKit'
  

  target 'Seoul ParkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Seoul ParkingUITests' do
    # Pods for testing
  end

end
