# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seoul Parking' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  
  # Pods for Seoul Parking

  target 'Seoul ParkingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Seoul ParkingUITests' do
    # Pods for testing
  end

end
